FROM python:3.12-slim
WORKDIR /app

COPY pyproject.toml .
COPY api     ./api
COPY worker  ./worker
COPY common  ./common

RUN pip install --no-cache-dir poetry \
 && poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-ansi

ENV CELERY_BROKER_URL=redis://redis:6379/0
CMD ["celery", "-A", "worker.worker", "worker", "--loglevel=info"]
