FROM python:3.12-slim
WORKDIR /app

COPY pyproject.toml .
COPY api     ./api
COPY worker  ./worker
COPY common  ./common

RUN pip install --no-cache-dir poetry \
 && poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-ansi

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
