name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or limitation
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Which area does this affect?
      options:
        - Agent/Tools
        - Configuration
        - Frontend/UI
        - Memory System
        - Observability
        - Deployment
        - Documentation
        - Other
    validations:
      required: false
