# CAA Benchmark Harness Configuration

# AWS Configuration
aws:
  region: "us-east-1"
  account_id: "123456789999"  # Update with your AWS account ID

# ECR Configuration
ecr:
  registry: "123456789999.dkr.ecr.us-east-1.amazonaws.com"  # Update with your account ID
  repositories:
    web_apps: "benchmark-harness/xben-web-apps"
    databases: "benchmark-harness/xben-databases"
    services: "benchmark-harness/xben-services"
    caa_agent: "benchmark-harness/caa-agent"
    caa_agent: "benchmark-harness/caa-agent"

# EKS Configuration
eks:
  cluster_name: "benchmark-harness-cluster"
  kubernetes_version: "1.31"
  namespace: "benchmark-harness"

# VPC Configuration
vpc:
  cidr: "10.0.0.0/8"  # Massive address space
  subnet_mask: 16      # /16 subnets = 65,534 IPs each

# Node Groups Configuration
node_groups:
  primary:
    instance_types: ["c5.2xlarge", "c5.4xlarge"]
    min_size: 10
    max_size: 100
    desired_size: 20
    disk_size: 100
    labels:
      workload: "benchmarks"
      node-type: "primary"
  
  performance:
    instance_types: ["c5.9xlarge", "c5.12xlarge"]
    min_size: 5
    max_size: 50
    desired_size: 10
    disk_size: 200
    labels:
      workload: "high-performance"
      node-type: "performance"

# Container Configuration
containers:
  platform: "linux/amd64"
  image_tag: "latest"
  build_timeout: 1800  # 30 minutes

# Deployment Configuration
deployment:
  health_checks:
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 5
  
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

# Benchmark Configuration
benchmarks:
  total_count: 104
  start_id: 1
  end_id: 104
  id_format: "XBEN-{:03d}-24"
  
  # Special configurations for specific benchmarks
  special_configs:
    "XBEN-066-24":
      components: 4  # db, haproxy, hrs_admin_router, mitmproxy
      description: "Complex multi-service benchmark"
    
    "XBEN-001-24":
      components: 2  # db, web app
      description: "Database + web application benchmark"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_retention_days: 30
  log_retention_days: 7

# Security Configuration
security:
  pod_security_standards: "restricted"
  network_policies: true
  rbac_enabled: true