# CAA Agent Runner Configuration

# Agent settings
agent:
  image: "123456789999.dkr.ecr.us-east-1.amazonaws.com/benchmark-harness/caa-agent:latest"
  max_concurrent: 5
  timeout_minutes: 60
  
# Bedrock settings
bedrock:
  provider: "bedrock"
  model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  region: "us-east-1"
  iterations: 150

# Kubernetes settings
kubernetes:
  namespace: "benchmark-harness"
  secret_name: "bedrock-credentials"
  ttl_seconds: 3600  # Keep completed jobs for 1 hour
  
# Resource limits
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

# Node selection
node_selector:
  workload: "benchmarks"

# Results settings
results:
  directory: "results"
  keep_logs: true
  keep_job_manifests: true