name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        uv sync
        uv add --dev pylint pytest pytest-mock
        # Ensure the package is installed in editable mode
        uv pip install -e .
    
    - name: Run Pylint
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export PYTHONPATH="${PWD}/src:${PYTHONPATH}"
        uv run pylint src/ --fail-under=9.5 --exit-zero
        echo "Pylint score:"
        uv run pylint src/ --score=y | grep "Your code has been rated"
    
    - name: Run Tests
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export PYTHONPATH="${PWD}/src:${PYTHONPATH}"
        uv run pytest tests/ -v
    
    - name: Check Pylint minimum score
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export PYTHONPATH="${PWD}/src:${PYTHONPATH}"
        uv run pylint src/ --fail-under=9.5